postprocessor:
  name: nystrom_max_vw
  APS_mode: False
  postprocessor_args:
    sigma: 0.5
    n_anchors: 200
    anchor_init: kmeans
    reg_lambda: 1.0e-4
    kmeans_iter: 50
    alpha: 0.05
    normalize: True
    score_mode: max
    variance_weighted: True
    feature_space: penultimate
  postprocessor_sweep: {}
