postprocessor:
  name: nystrom_softmax_vw_mlpca_minmax
  APS_mode: False
  postprocessor_args:
    sigma: 0.5
    n_anchors: 200
    anchor_init: kmeans
    reg_lambda: 1.0e-4
    kmeans_iter: 50
    alpha: 0.05
    normalize: True
    score_mode: softmax
    variance_weighted: False
    feature_space: multilayer_pca
    pca_layers: [2, 3, 4]
    pca_components: 128
    pool_mode: minmax
  postprocessor_sweep: {}
