postprocessor:
  name: rff_predictor_aware_vw_mlminmax_clip
  APS_mode: False
  postprocessor_args:
    sigma: 0.5
    D: 2048
    alpha: 0.05
    normalize: True
    normalize_phi: True
    variance_weighted: True
    score_mode: predictor_aware
    # Multilayer minmax (Tej-style)
    pca_layers: [1, 2, 3, 4]
    pool_mode: minmax
    yosinski_weights: [0.712, 0.734, 0.771, 0.790]
    # CLIP
    clip_backbone: ViT-B/16
    data_root: ./data
