postprocessor:
  name: rff_predictor_aware_vw_allpca
  postprocessor_args:
    sigma: 0.5
    D: 1024
    alpha: 0.05
    normalize: True
    normalize_phi: True
    feature_space: multilayer_pca
    pca_layers: [0, 1, 2, 3, 4]
    pca_components: 128
    fisher_weighting: True
    score_mode: predictor_aware
    variance_weighted: True
    APS_mode: True
  postprocessor_sweep:
    sigma: [0.1, 0.5, 1.0, 2.0]
    D: [512, 1024, 2048]
    alpha: [0.025, 0.05, 0.10]
  hyperparam_search_done: False
