postprocessor:
  name: rff_softmax_vw_concat
  APS_mode: False
  postprocessor_args:
    sigma: 0.5
    D: 2048
    alpha: 0.05
    normalize: True
    normalize_phi: True
    variance_weighted: True
    score_mode: softmax
    clip_backbone: ViT-B/16
    data_root: ./data
