#!/usr/bin/env python3
"""Remove failed OpenOOD log records.

By default this script only prints what it would delete. Pass --apply to delete
the matching .out/.err log files. Prefer --from-list with a list generated by
scan_failed_log_records.py when cleaning a remote logs directory.
"""

from __future__ import annotations

import argparse
from pathlib import Path


FAILED_RECORDS = {
    "none_config_type_error": [
        "rff_centroid_vw_mlpca_minmax_imagenet_5016174",
        "rff_max_vw_mlminmax_5116952_0",
        "rff_max_vw_mlminmax_5116952_1",
        "rff_max_vw_mlminmax_5116952_2",
        "rff_max_vw_mlminmax_5117315_0",
        "rff_max_vw_mlminmax_5117315_1",
        "rff_max_vw_mlminmax_5117315_2",
        "rff_max_vw_mlpca_imagenet_5016175",
        "rff_max_vw_mlpca_minmax_imagenet_5016239",
        "rff_max_vw_vit_b16_5016168",
        "rff_predictor_aware_vw_mlminmax_5116954_0",
        "rff_predictor_aware_vw_mlminmax_5116954_1",
        "rff_predictor_aware_vw_mlminmax_5116954_2",
        "rff_predictor_aware_vw_mlminmax_5117317_0",
        "rff_predictor_aware_vw_mlminmax_5117317_1",
        "rff_predictor_aware_vw_mlminmax_5117317_2",
        "rff_softmax_vw_mlminmax_5116953_0",
        "rff_softmax_vw_mlminmax_5116953_1",
        "rff_softmax_vw_mlminmax_5116953_2",
        "rff_softmax_vw_mlminmax_5117316_0",
        "rff_softmax_vw_mlminmax_5117316_1",
        "rff_softmax_vw_mlminmax_5117316_2",
    ],
    "no_gpu_or_cpu_only": [
        "rff_entropy_vw_4384416_0",
        "rff_entropy_vw_4384416_1",
        "rff_entropy_vw_4384416_2",
        "rff_entropy_vw_4386175_0",
        "rff_entropy_vw_4386175_1",
        "rff_entropy_vw_4386175_2",
        "rff_entropy_vw_4470803_0",
        "rff_entropy_vw_4470803_1",
        "rff_entropy_vw_4470803_2",
        "rff_exclusive_novw_4143922_0",
        "rff_exclusive_novw_4143922_1",
        "rff_exclusive_novw_4143922_2",
        "rff_max_vw_4124018_2",
        "rff_softmax_vw_mlpca_4510234_1",
        "rff_twohop_centroid_vw_4514655_0",
        "rff_twohop_centroid_vw_4514655_1",
        "rff_twohop_vw_4472091_0",
        "rff_twohop_vw_4472091_1",
        "rff_twohop_vw_4472091_2",
    ],
    "shape_mismatch": [
        "rff_max_vw_mlminmax_5061356_0",
        "rff_max_vw_mlminmax_5061356_1",
        "rff_max_vw_mlminmax_5061356_2",
        "rff_predictor_aware_vw_mlminmax_5061358_0",
        "rff_predictor_aware_vw_mlminmax_5061358_1",
        "rff_predictor_aware_vw_mlminmax_5061358_2",
        "rff_softmax_vw_mlminmax_5061357_0",
        "rff_softmax_vw_mlminmax_5061357_1",
        "rff_softmax_vw_mlminmax_5061357_2",
        "rff_softmax_vw_mlpca_kpca_4629002_0",
        "rff_softmax_vw_mlpca_kpca_4629002_1",
        "rff_softmax_vw_mlpca_kpca_4629002_2",
        "rff_softmax_vw_mlpca_kpca_4638081_0",
        "rff_softmax_vw_mlpca_kpca_4638081_1",
        "rff_softmax_vw_mlpca_kpca_4638081_2",
    ],
    "view_vs_reshape_bug": [
        "rff_max_vw_whiten_pc_4508133_0",
        "rff_max_vw_whiten_pc_4508133_1",
        "rff_max_vw_whiten_pc_4508133_2",
        "rff_softmax_vw_whiten_pc_4508134_0",
        "rff_softmax_vw_whiten_pc_4508134_1",
        "rff_softmax_vw_whiten_pc_4508134_2",
    ],
    "missing_clip_dependency": [
        "rff_dual_gated_vw_4902509_0",
        "rff_dual_gated_vw_4902509_1",
        "rff_dual_gated_vw_4902509_2",
        "rff_dual_gated_vw_4902509_3",
        "rff_max_vw_vit_b16_4900730",
    ],
    "dual_gated_type_error": [
        "rff_dual_gated_vw_5016171_0",
        "rff_dual_gated_vw_5016171_1",
        "rff_dual_gated_vw_5016171_2",
        "rff_dual_gated_vw_5016171_3",
    ],
    "missing_or_inaccessible_data": [
        "rff_centroid_vw_mlpca_minmax_4820344_3",
        "rff_centroid_vw_mlpca_minmax_4821531_3",
        "rff_centroid_vw_mlpca_minmax_4824664_3",
    ],
    "missing_diag_attribute": [
        "rff_max_vw_4345335_0",
        "rff_max_vw_4345335_1",
    ],
}


def read_records_from_list(path: Path) -> list[str]:
    records = []
    seen = set()
    for line in path.read_text().splitlines():
        record = line.strip()
        if not record or record.startswith("#"):
            continue
        if record in seen:
            continue
        seen.add(record)
        records.append(record)
    return records


def iter_targets(logs_dir: Path, records_by_reason: dict[str, list[str]]):
    for reason, records in records_by_reason.items():
        for record in records:
            for suffix in (".out", ".err"):
                yield reason, record, logs_dir / f"{record}{suffix}"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Delete failed OpenOOD log records from a logs directory."
    )
    parser.add_argument(
        "--logs-dir",
        type=Path,
        default=Path("logs"),
        help="Directory containing .out/.err log files. Default: logs",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually delete files. Without this flag, only print a dry run.",
    )
    parser.add_argument(
        "--from-list",
        type=Path,
        help="Read record base names from a text file, one per line.",
    )
    args = parser.parse_args()

    logs_dir = args.logs_dir.expanduser().resolve()
    if args.from_list:
        list_path = args.from_list.expanduser().resolve()
        records_by_reason = {"from_list": read_records_from_list(list_path)}
    else:
        records_by_reason = FAILED_RECORDS

    existing = []
    missing = []
    seen_records = set()

    for reason, record, path in iter_targets(logs_dir, records_by_reason):
        seen_records.add(record)
        if path.exists():
            existing.append((reason, record, path))
        else:
            missing.append(path)

    action = "Deleting" if args.apply else "Would delete"
    print(f"{action} {len(existing)} files from {logs_dir}")
    print(f"Records targeted: {len(seen_records)}")
    if args.from_list:
        print(f"Record list: {list_path}")

    current_reason = None
    for reason, record, path in existing:
        if reason != current_reason:
            current_reason = reason
            print(f"\n[{reason}]")
        print(f"  {path.name}")
        if args.apply:
            path.unlink()

    if missing:
        print(f"\nAlready absent: {len(missing)} files")
        for path in missing:
            print(f"  {path.name}")

    if not args.apply:
        print("\nDry run only. Re-run with --apply to delete these files.")


if __name__ == "__main__":
    main()
